In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("heights.csv")

In [6]:
df

         earn     height     sex  ed  age   race
0     50000.0  74.424439    male  16   45  white
1     60000.0  65.537543  female  16   58  white
2     30000.0  63.629198  female  16   29  white
3     50000.0  63.108562  female  16   91  other
4     51000.0  63.402484  female  17   39  white
...       ...        ...     ...  ..  ...    ...
1187  19000.0  72.165733    male  12   29  white
1188  15000.0  61.135800  female  18   82  white
1189   8000.0  63.664164  female  12   33  white
1190  60000.0  71.925836    male  12   50  white
1191   6000.0  68.368486    male  12   27  white

[1192 rows x 6 columns]

In [5]:
df.head()

      earn     height     sex  ed  age   race
0  50000.0  74.424439    male  16   45  white
1  60000.0  65.537543  female  16   58  white
2  30000.0  63.629198  female  16   29  white
3  50000.0  63.108562  female  16   91  other
4  51000.0  63.402484  female  17   39  white

In [10]:
print("\nSummary Statistics:")
print(df.describe())

Summary Statistics:
                earn       height           ed          age
count    1192.000000  1192.000000  1192.000000  1192.000000
mean    23154.773490    66.915154    13.504195    41.378356
std     19472.296925     3.853968     2.420175    15.867428
min       200.000000    57.503219     3.000000    18.000000
25%     10000.000000    64.009746    12.000000    29.000000
50%     20000.000000    66.451265    13.000000    38.000000
75%     30000.000000    69.848100    16.000000    51.000000
max    200000.000000    77.051282    18.000000    91.000000

In [13]:
missing_values = df.isnull().sum()
print("\nMissing Values:")
print(missing_values)

Missing Values:
earn      0
height    0
sex       0
ed        0
age       0
race      0
dtype: int64

In [15]:
df['earn'].fillna(df['earn'].mean(), inplace=True)
df['height'].fillna(df['height'].mean(), inplace=True)
df['sex'].fillna(df['sex'].mode()[0], inplace=True)
df['ed'].fillna(df['ed'].mode()[0], inplace=True)
df['age'].fillna(df['age'].mean(), inplace=True)
df['race'].fillna(df['race'].mode()[0], inplace=True)

In [22]:
df['age'] = df['age'].astype(int)
df['race'] = df['race'].astype('category')
df['earn'] = df['earn'].astype(int)
df['height'] = df['height'].astype(int)
df['sex'] = df['sex'].astype('category')
df['ed'] = df['ed'].astype(int)

In [23]:
print("\nUnique values in 'earn':", df['earn'].unique())
print("Unique values in 'height':", df['height'].unique())
print("Unique values in 'sex':", df['sex'].unique())
print("\nUnique values in 'ed':", df['ed'].unique())
print("Unique values in 'age':", df['age'].unique())
print("Unique values in 'race':", df['race'].unique())

Unique values in 'earn': [ 50000  60000  30000  51000   9000  29000  32000   2000  27000   6530
  12000  22000  17000  40000  44000   7000  53000   5000  14000   5500
  34000  10000  41000  15000  25000  75000   7500  21000   3000  24000
  11000  18700  20000   3500  13000   6000  35000   4000  16000  16500
   3840    200  26000   2500   8000   2400   1200    700  18000  16040
  33000  37000  38000  27500  70000  23000  45000   5688  43000   1000
   6600  90000  19000  65000  49000 125000  69000  62000 170000  32750
  36000  42000  28000  10500   2100   3192  17500  52000  14500  80000
  23900  23500 175000 100000 148000   6500   5124 110000   5800  89000
   1500  31000    600  20112  57000  55000  12500  17600  16400 105000
  18600   7200   8500  31500  95000  35900  21500   4500   9500   4100
   1800 123000   7600  13800   5300   4700   1700   5400  96000    400
  58000  19005   6108   4416  48000   6200  47000    265  18720  85000
 200000   1400   3600]
Unique values in 'height': [74 65 63 64 61 72 69 68 67 73 62 71 76 66 60 59 70 75 58 57 77]
Unique values in 'sex': ['male', 'female']
Categories (2, object): ['female', 'male']

Unique values in 'ed': [16 17 15 12 11 14 13 18 10  8  9  6  5  7  4  3]
Unique values in 'age': [45 58 29 91 39 26 49 46 21 65 34 27 51 35 44 55 22 41 60 38 33 25 31 78
 57 30 32 18 56 28 43 68 52 53 47 67 63 61 36 23 20 73 89 79 66 37 40 24
 42 62 71 69 50 64 48 74 77 54 82 59 76 75 81 72 19 84 83 85 88 87 80 86]
Unique values in 'race': ['white', 'other', 'hispanic', 'black']
Categories (4, object): ['black', 'hispanic', 'other', 'white']

In [24]:
df.reset_index(drop=True, inplace=True)

In [25]:
print("\nCleaned DataFrame:\n", df)

Cleaned DataFrame:
        earn  height     sex  ed  age   race
0     50000      74    male  16   45  white
1     60000      65  female  16   58  white
2     30000      63  female  16   29  white
3     50000      63  female  16   91  other
4     51000      63  female  17   39  white
...     ...     ...     ...  ..  ...    ...
1187  19000      72    male  12   29  white
1188  15000      61  female  18   82  white
1189   8000      63  female  12   33  white
1190  60000      71    male  12   50  white
1191   6000      68    male  12   27  white

[1192 rows x 6 columns]